career_choice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('stream_select.urls'))
]

stream_select/urls.py
from django.conf.urls import url
from stream_select import views

app_name = 'stream_select'

urlpatterns = [url(r'^$', views.HomeView, name='home'),
               url(r'^questions/$', views.QuestionView, name='ques'),
               url(r'^result/$', views.calc, name='result'),
               ]

stream_select/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

stream_select/views.py
import matplotlib
matplotlib.use("Agg")
from django.shortcuts import render, redirect
import matplotlib.pyplot as plt
import numpy as np
from io import BytesIO
import base64
from django.core.urlresolvers import reverse

op1, op2, op3, op4, op5, op6, op7, op8, op9, op10, op11, op12, op13, op14, op15, op16, op17 = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
streams = ['mechanical', 'civil', 'electrical', 'electronics', 'computer', 'software']
val = [int(0)] * 6

def HomeView(request):
    template = 'stream_select/home.html'
    context = {}
    
    return render(request, template, context)

def QuestionView(request):
    global op1, op2, op3, op4, op5, op6, op7, op8, op9, op10, op11, op12, op13, op14, op15, op16, op17
    context = {}
    template = 'stream_select/ques.html'
    if request.method == "POST":
        if request.POST.get('opt1') != None:
            op1 = request.POST.get('opt1')
        if request.POST.get('opt2') != None:
            op2 = request.POST.get('opt2')
        if request.POST.get('opt3') != None:
            op3 = request.POST.get('opt3')
        if request.POST.get('opt4') != None:
            op4 = request.POST.get('opt4')
        if request.POST.get('opt5') != None:
            op5 = request.POST.get('opt5')
        if request.POST.get('opt6') != None:
            op6 = request.POST.get('opt6')
        if request.POST.get('opt7') != None:
            op7 = request.POST.get('opt7')
        if request.POST.get('opt8') != None:
            op8 = request.POST.get('opt8')
        if request.POST.get('opt9') != None:
            op9 = request.POST.get('opt9')
        if request.POST.get('opt10') != None:
            op10 = request.POST.get('opt10')
        if request.POST.get('opt11') != None:
            op11 = request.POST.get('opt11')
        if request.POST.get('opt12') != None:
            op12 = request.POST.get('opt12')
        if request.POST.get('opt13') != None:
            op13 = request.POST.get('opt13')
        if request.POST.get('opt14') != None:
            op14 = request.POST.get('opt14')
        if request.POST.get('opt15') != None:
            op15 = request.POST.get('opt15')
        if request.POST.get('opt16') != None:
            op16 = request.POST.get('opt16')
        if request.POST.get('opt17') != None:
            op17 = request.POST.get('opt17')
        print(op1, op2, op3, op4, op5, op6, op7, op8, op9, op10, op11, op12, op13, op14, op15, op16, op17)
        return redirect(reverse('stream_select:result'))

    return render(request, template, context)

def calc(request):
    global op1, op2, op3, op4, op5, op6, op7, op8, op9, op10, op11, op12, op13, op14, op15, op16, op17, streams, val

    val[5] = (int(op1)*20) + (int(op2)*50) + (int(op3)*30)
    val[4] = (int(op3)*30) + (int(op4)*20) + (int(op5)*30) + (int(op7)*20)
    val[3] = (int(op6)*40) + (int(op7)*40) + (int(op8)*20)
    val[2] = (int(op8)*20) + (int(op9)*40) + (int(op10)*40)
    val[0] = (int(op11)*20) + (int(op12)*30) + (int(op13)*20) + (int(op17)*30)
    val[1] = (int(op14)*20) + (int(op15)*40) + (int(op16)*40)

    template = 'stream_select/result.html'
    context = {'mechanical': val[0], 'civil': val[1],
               'electrical': val[2], 'electronics': val[3],
               'computer' : val[4], 'software':val[5]
               }
    print(context)
    fig = plt.figure()
    y_bos = np.arange(len(streams))
    plt.bar(y_bos, val, align='center', alpha = 0.5)
    plt.xticks(y_bos, streams)
    plt.ylabel('Usage')
    plt.title('Result')
    img = BytesIO()
    fig.savefig(img, format='png')
    context['graph'] = base64.b64encode(img.getvalue())
    return render(request, template, context)

stream_select/templates/stream_select/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Career Choice</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
.parent {
  text-align: center;
}
  .margin {margin-bottom: 45px;}
  .bg-1 {
      background-color: #1abc9c; /* Green */
      color: #ffffff;
  }
  .bg-2 {
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
  .bg-3 {
      background-color: #ffffff; /* White */
      color: #555555;
  }
  .bg-4 {
      background-color: #2f2f2f; /* Black Gray */
      color: #fff;
  }
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }
.mailto{
  display:block;
  width:100px;
  height:20px;
}
  </style>
</head>
<body>
{% load static%}

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">

      </button>
      <a class="navbar-brand" href="#">Career Choice</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a class="mailto" href="mailto:jindalmayank78@gmail.com">Contact Us</a></li>

        </ul>
    </div>
  </div>
</nav>
<!-- First Container -->
<div class="container-fluid bg-1 text-center">
  <h3 class="margin">Career Choice</h3>
  <img src="{% static 'stream_select/Star.png' %}" class="img-responsive margin img-circle margin" style="display:inline" alt="Image" width="350" height="350">
  <h3>HOW DO I CHOOSE THE RIGHT CAREER?</h3>
<p>Get answers to all these questions and much more.
CareerChoice brings to you scientific and meticulously designed Psychometric Career Assessment to discover your true potential and interest.</p>
</div>

<!-- Second Container -->
<div class="container-fluid bg-2  text-center">
  <h3 class="margin">WHAT CAREER SHOULD I CHOOSE?</h3>
<p>
Which career stream should I choose ?</p>
<p>What to do after 10th or 12th ?</p>
<p>There are so many options which is right for me ?</p>
<p>Should I follow my family legacy ?</p>
<p>Am I a right fit to pursue science or should I choose commerce or arts ?</p>
<p>Do I have what it takes to be ...........?</p>
<p>Should I follow the advices of my relatives or friends ?</p>
<p>Is ........... the only professions in the world ?


</p>
  <a href="{% url 'stream_select:ques' %}" class="slide_page">
    Get Started
  </a>
</div>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center">
  <h3 class="margin">Who Are We?</h3><br>
  <div class="row">
    <div class="col-sm-2" >
<img src="{% static 'stream_select/Sahaj.jpg' %}" class="img-responsive margin" style="width:100%" alt="Image">
<p>Sahaj Singh Sachdeva</p>
<p> BML Munjal University</p>
      <p> +91  857 00 22 540</p>
    </div>
    <div class="col-sm-2">
      <img src="{% static 'stream_select/Mayank.jpg' %}" class="img-responsive margin" style="width:100%" alt="Image">
      <p>Mayank Jindal</p>
<p> BML Munjal University</p>
<p> +91  868 90 48 490</p>

    </div>
    <div class="col-sm-2">
      <img src="{% static 'stream_select/Divyanshu.jpg' %}" class="img-responsive margin" style="width:100%" alt="Image">
      <p>Divyanshu Gupta</p>
<p> BML Munjal University</p>
<p> +91  857 10 25 499</p>

    </div>

    <div class="col-sm-2">
      <img src="{% static 'stream_select/akshat.jpg' %}" class="img-responsive margin" style="width:100%" alt="Image">
      <p>Akshat Bhandari</p>
<p> BML Munjal University</p>
<p> +91  981 12 06 343</p>

    </div>
    <div class="col-sm-2">
      <img src="{% static 'stream_select/AGL.jpg' %}" class="img-responsive margin" style="width:100%" alt="Image">
      <p>Akshay Garg</p>
<p> BML Munjal University</p>
<p> +91  857 19 67 954</p>

    </div>
     <div class="col-sm-2">
      <img src="{% static 'stream_select/akshay.jpg' %}" class="img-responsive margin" style="width:100%" alt="Image">
      <p>Akshay Goswami</p>
<p> BML Munjal University</p>
<p> +91  989 98 62 470</p>

    </div>

  </div>
</div>

<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p>Brought to you by CAREER CHOICE  &nbsp;    <span style="font-size:200%;color:red;">&hearts;</span> &nbsp; </p>
<div class="copyright">
&copy; 2017, BML Munjal University, All rights reserved
</div>
</footer>

</body>
</html>

stream_select/templates/stream_select/ques.html
<!DOCTYPE html>
<html lang="en">
<head>

  <title>Career Choice</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <script>
        function onClicked(){
        $(location).attr('href','/result')
        }
    </script>
  <style>
  body {
      font: 15px Montserrat, sans-serif;
      line-height: 1.3;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
  .margin {margin-bottom: 45px;}
  .bg-1 {
      background-color: #1abc9c; /* Green */
      color: #ffffff;
  }
  .bg-2 {
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
  .bg-3 {
      background-color: #ffffff; /* White */
      color: #555555;
  }
  .bg-4 {
      background-color: #2f2f2f; /* Black Gray */
      color: #fff;
  }
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }
  </style>
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'stream_select:home' %}">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a class="mailto" href="mailto:jindalmayank78@gmail.com">Contact Us</a></li>
      </ul>
    </div>
  </div>
</nav>
{% load static %}
<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center">
<img src="{% static 'stream_select/what.jpg' %}" class="img-responsive img-circle margin" style="display:inline" alt="Image" width="350" height="350">
  <h3 class="margin">What To Do?</h3><br>
  <center>
      <p>Simply answer these questions..</p>

      </center>
</div>
<form method='POST' action=''>{% csrf_token %}

<!-- First Question -->
<div class="container-fluid bg-1 text-center">
<p>Q1. Do you like to play games on computers?</p>

    <label class="radio-inline">
      <input type="radio" name="opt1" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt1" value="0">No
    </label>



</div>

<!-- Second Question -->
<div class="container-fluid bg-2 text-center">
<p>Q2. Would you like to make your own games?</p>
  <label class="radio-inline">
      <input type="radio" name="opt2" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt2" value="0">No
    </label>


</div>

<!-- Third Question -->
<div class="container-fluid bg-1 text-center">
<p>Q3. Are you curious to know how your mails, chat messages etc. are sent from your device to your friends device ?</p>
  <label class="radio-inline">
      <input type="radio" name="opt3" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt3" value="0">No
    </label>

  </div>

<!-- Fourth Question -->
<div class="container-fluid bg-2 text-center">
<p>Q4. Are you curious about what is really happening inside your computer?</p>
  <label class="radio-inline">
      <input type="radio" name="opt4" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt4" value="0">No
    </label>

</div>


<!-- Fifth Question -->
<div class="container-fluid bg-1 text-center">
<p>Q5. Would you like to design/make your own computer?</p>
  <label class="radio-inline">
      <input type="radio" name="opt5" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt5" value="0">No
    </label>

  </div>

<!-- Sixth Question -->
<div class="container-fluid bg-2 text-center">
<p>Q6. Do you get fascinated by seeing electronic chips and other such gadgetry?</p>
  <label class="radio-inline">
      <input type="radio" name="opt6" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt6" value="0">No
    </label>

</div>

<!-- Seventh Question -->
<div class="container-fluid bg-1 text-center">
<p>Q7. Are you curious about how signals are transferred in between electronic devices?</p>
  <label class="radio-inline">
      <input type="radio" name="opt7" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt7" value="0">No
    </label>
  </div>

<!-- Eighth Question -->
<div class="container-fluid bg-2 text-center">
<p>Q8. Do you like electrical circuits and devices?</p>
  <label class="radio-inline">
      <input type="radio" name="opt8" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt8" value="0">No
    </label>


</div>

<!-- Ninth Question -->
<div class="container-fluid bg-1 text-center">
<p>Q9. Would you like to design/make your own electrical circuits and devices?</p>
  <label class="radio-inline">
      <input type="radio" name="opt9" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt9" value="0">No
    </label>

  </div>

<!-- Tenth Question -->
<div class="container-fluid bg-2 text-center">
<p>Q10. Would you like to work in an environment with power grids, transformers etc?</p>
  <label class="radio-inline">
      <input type="radio" name="opt10" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt10" value="0">No
    </label>


</div>

<!-- Eleventh Question -->
<div class="container-fluid bg-1 text-center">
<p>Q11. Are you fascinated by 'how machines work'?</p>
  <label class="radio-inline">
      <input type="radio" name="opt11" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt11" value="0">No
    </label>

  </div>

<!-- Twelth Question -->
<div class="container-fluid bg-2 text-center">
<p>Q12. Would you like to design/make your own machines and mechanical systems?</p>
  <label class="radio-inline">
      <input type="radio" name="opt12" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt12" value="0">No
    </label>


</div>

<!-- Thirteenth Question -->
<div class="container-fluid bg-1 text-center">
<p>Q13. Do you like cars? Are you curious to know what is really happening under that hood?</p>
 <label class="radio-inline">
      <input type="radio" name="opt13" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt13" value="0">No
    </label>

  </div>

<!-- Forteenth Question -->
<div class="container-fluid bg-2 text-center">
<p>Q14. Are you fascinated by 'how buildings are designed/constructed'?</p>
  <label class="radio-inline">
      <input type="radio" name="opt14" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt14" value="0">No
    </label>


</div>

<!-- Fifteenth Question -->
<div class="container-fluid bg-1 text-center">
<p>Q15. Would you like to design/construct buildings and undertake big architectural projects?</p>
    <label class="radio-inline">
      <input type="radio" name="opt15" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt15" value="0">No
    </label>

</div>


<!-- Sixteenth Question -->
<div class="container-fluid bg-2 text-center">
<p>Q16. Can you work in a construction environment?</p>
    <label class="radio-inline">
      <input type="radio" name="opt16" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt16" value="0">No
    </label>

</div>

<!-- Seventeenth Question -->
<div class="container-fluid bg-1 text-center">
<p>Q17. Can you work in an environment with huge machinery and their loud noise?</p>
    <label class="radio-inline">
      <input type="radio" name="opt17" value="1">Yes
    </label>
    <label class="radio-inline">
      <input type="radio" name="opt17" value="0">No
    </label>

</div>

<div class="container-fluid bg-2 text-center">

  <input type="submit" class="btn btn-info" value="Submit"  >

   <!-- <a href="{% url 'stream_select:result' %}" class="slide_page">See Results</a> -->
</div>

    </form>

<!-- Footer -->
<footer class="container-fluid bg-1 text-center">
  <p>Brought to you by CAREER CHOICE  &nbsp;    <span style="font-size:200%;color:red;">&hearts;</span> &nbsp;</p>
<div class="copyright">
&copy; 2017, BML Munjal University, All rights reserved
</div>
</footer>
</body>
</html>

stream_select/templates/stream_select/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Career Choice</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
.parent {
  text-align: center;
}
  .margin {margin-bottom: 45px;}
  .bg-1 {
      background-color: #1abc9c; /* Green */
      color: #ffffff;
  }
  .bg-2 {
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
  .bg-3 {
      background-color: #ffffff; /* White */
      color: #555555;
  }
  .bg-4 {
      background-color: #2f2f2f; /* Black Gray */
      color: #fff;
  }
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }
.mailto{
  display:block;
  width:100px;
  height:20px;
}
  </style>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'stream_select:home' %}">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a class="mailto" href="mailto:jindalmayank78@gmail.com">Contact Us</a></li>
      </ul>
    </div>
  </div>
</nav>
{% load static %}
<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center">
  <h3 class="margin">Take your decision wisely!</h3><br>
  <center>
      <p>Here is what we recommend for you. Following are your interests in each stream out of 100.</p>
<img src="data:image/png;base64,{{graph}}" class="img-responsive margin" style="display:inline" alt="Image" width="550" height="550">
      </center>
</div>

<div class="container-fluid bg-1 text-center">
    <p>Mechanical :  {{mechanical}}</p>
</div>

<div class="container-fluid bg-2 text-center">
    <p>Civil :  {{civil}}</p>
</div>

<div class="container-fluid bg-1 text-center">
    <p>Electrical :  {{electrical}}</p>
</div>

<div class="container-fluid bg-2 text-center">
    <p>Electronics :  {{electronics}}</p>
</div>

<div class="container-fluid bg-1 text-center">
    <p>Computer :  {{computer}}</p>
</div>

<div class="container-fluid bg-2 text-center">
    <p>Software :  {{software}}</p>
</div>

<!-- Footer -->
<footer class="container-fluid bg-1 text-center">
  <p>Brought to you by CAREER CHOICE  &nbsp;    <span style="font-size:200%;color:red;">&hearts;</span> &nbsp;</p>
<div class="copyright">
&copy; 2017, BML Munjal University, All rights reserved
</div>
</footer>

</body>
</html>